import {buildReplyDraft} from '../sarberki-core.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {capacityInput,stageFacts} from '../booking-filter.mjs';
import {createBookingCaseStore} from '../booking-cases.mjs';
import {buildAvailabilityOptions} from '../netlify/functions/availability-options.mjs';
import {splitRequestFromText} from '../split-units.mjs';
const stay={arrival:'2026-10-23',departure:'2026-10-25',guests:4,adults:4};
const source=counts=>async input=>({...input,availability:(counts[input.cabin]||0)>0?'available':'unavailable',availableUnits:counts[input.cabin]||0,source:'MOCK',checkedAt:new Date().toISOString()});
test('switching from AB to Deluxe drops historical split placement',()=>{const i=capacityInput({...stay,unit:'Deluxe',split_request_text:'Osztott A+B egymás mellett'});assert.equal(i.placement,undefined);});
test('reviewed split C type takes precedence over historical AB text',()=>{const i=capacityInput({...stay,unit:'Osztott C',split_request_text:'Osztott A+B'});assert.equal(i.placement.c,1);assert.equal(i.placement.ab,0);});
test('changing number of homogeneous split units changes required inventory',()=>{const i=capacityInput({...stay,unit:'Osztott',units_requested:3},'Osztott A+B');assert.equal(i.placement.ab,3);});
for(const [guests,counts,expected]of [[6,{splitC:2},2],[10,{splitC:3},3],[8,{splitA:4},4],[12,{splitA:2,splitC:2},4]])test(`${guests} guests can use verified repeated split units`,async()=>{const r=await buildAvailabilityOptions({...stay,guests,adults:guests},source(counts));assert.ok(r.available_options.some(o=>o.units===expected&&o.key.startsWith('split')));});
for(const text of ['two 2-person split apartments','zwei 2-Personen geteilte Apartments','dva 2-osebna deljena apartmaja'])test(`multilingual split unit count: ${text}`,()=>{assert.equal(splitRequestFromText(text).requestedAB,2);});
test('negated adjacency does not require a physical pair',()=>{assert.equal(splitRequestFromText('Osztott A+B; nem szükséges, hogy egymás mellett legyenek.').requiresAdjacent,false);});
test('historical message is recorded without overwriting newer facts',()=>{let n=0;const s=createBookingCaseStore({id:()=>`case-${++n}`});const a=s.ingest({sender:'guest@test.invalid',thread_id:'thread',message_id:'new',text:'Új időpont',received_at:'2026-10-08T18:00:00Z'},{...stay,arrival:'2026-11-06',departure:'2026-11-08'});s.save(a.bookingCase.id,{...a.bookingCase.state,quote:{total:100},availability:{verified:true}});const b=s.ingest({sender:'guest@test.invalid',thread_id:'thread',message_id:'old',text:'Régi időpont',received_at:'2026-10-08T17:00:00Z'},stay);assert.equal(b.bookingCase.state.values.arrival,'2026-11-06');assert.equal(b.bookingCase.state.quote.total,100);assert.equal(b.bookingCase.messages.length,2);assert.equal(b.resolution.status,'historical');});
test('child count modification invalidates the previous age list',()=>{const s=createBookingCaseStore({id:()=> 'case-1'}),e={sender:'guest@test.invalid',thread_id:'thread',text:'Gyermekek'};s.ingest({...e,message_id:'one'},{...stay,adults:2,children:2,child_ages:'7, 11'});const b=s.ingest({...e,message_id:'two'},{children:1});assert.equal(b.bookingCase.state.values.child_ages,'');assert.equal(b.bookingCase.facts.child_ages.status,'missing');});
test('new whole type clears previous split requirement in stored case',()=>{const s=createBookingCaseStore({id:()=> 'case-1'}),e={sender:'guest@test.invalid',thread_id:'thread',text:'Kérés'};s.ingest({...e,message_id:'one'},{...stay,unit:'Osztott',split_request_text:'Osztott A+B'});const b=s.ingest({...e,message_id:'two'},{unit:'Deluxe'});assert.equal(b.bookingCase.state.values.split_request_text,'');});
for(const values of [{arrival:'2026-02-30'},{arrival:'2026-10-25',departure:'2026-10-23'},{children:-1},{adults:'kettő'},{arrival:'2026-10-23',departure:'2026-10-25',nights:3}])test(`invalid facts are not marked known: ${JSON.stringify(values)}`,()=>{assert.ok(Object.values(stageFacts(values)).some(f=>f.status==='contradictory'));});

test('contradictory mixed unit count is rejected before contacting the source',async()=>{let calls=0;await assert.rejects(buildAvailabilityOptions({...stay,units:3,cabin:'split',placement:{ab:1,c:1,adjacent:false,exactIds:[]}},async()=>{calls++;}),/ellentmondásos/u);assert.equal(calls,0);});
test('an explicitly separate booking in the same thread is not silently merged',()=>{let n=0;const s=createBookingCaseStore({id:()=>`case-${++n}`});const e={sender:'guest@test.invalid',thread_id:'thread'};const a=s.ingest({...e,message_id:'one',text:'Deluxe érdeklődés'},stay);const b=s.ingest({...e,message_id:'two',text:'Egy külön foglalást szeretnék.'},{...stay,arrival:'2026-11-06',departure:'2026-11-08'});assert.equal(b.resolution.status,'ambiguous');assert.notEqual(b.bookingCase.id,a.bookingCase.id);assert.equal(s.get(a.bookingCase.id).state.values.arrival,stay.arrival);});

test('explicit old-arrival replacement with checkout updates the linked stay and revokes the quote',()=>{
 const s=createBookingCaseStore({id:()=> 'dates-case'}),e={sender:'guest@test.invalid',thread_id:'dates'};const a=s.ingest({...e,message_id:'one',text:'Első időpont'},stay);s.save(a.bookingCase.id,{...a.bookingCase.state,quote:{total:100},availability:{verified:true}});
 const b=s.ingest({...e,message_id:'two',text:'Az érkezést módosítanánk: 2026.10.23 helyett 2026.10.30; távozás: 2026.11.01.'},{},{intent:'modification_request'});assert.equal(b.bookingCase.state.values.arrival,'2026-10-30');assert.equal(b.bookingCase.state.values.departure,'2026-11-01');assert.equal(b.bookingCase.state.quote,null);assert.equal(b.bookingCase.state.availability,null);assert.equal(b.bookingCase.dateReview.previousDates.arrival,stay.arrival);
});
test('unresolved multi-date correction does not reuse the previous capacity or dates',()=>{
 const s=createBookingCaseStore({id:()=> 'dates-case'}),e={sender:'guest@test.invalid',thread_id:'dates'};s.ingest({...e,message_id:'one',text:'Első időpont'},stay);const b=s.ingest({...e,message_id:'two',text:'Új időpont: 2026.10.30 vagy 2026.11.06, távozás 2026.11.08.'},{},{intent:'modification_request'});assert.equal(b.bookingCase.state.values.arrival,'');assert.equal(b.bookingCase.state.values.departure,'');assert.equal(b.bookingCase.dateReview.status,'unverified');assert.equal(b.bookingCase.dateReview.previousDates.arrival,stay.arrival);
});
test('mismatching previous arrival is not accepted as a proven correction',()=>{
 const s=createBookingCaseStore({id:()=> 'dates-case'}),e={sender:'guest@test.invalid',thread_id:'dates'};s.ingest({...e,message_id:'one',text:'Első időpont'},stay);const b=s.ingest({...e,message_id:'two',text:'2026.10.16 helyett 2026.10.30; távozás 2026.11.01.'},{},{intent:'modification_request'});assert.equal(b.bookingCase.dateReview.status,'unverified');assert.equal(b.bookingCase.state.values.arrival,'');
});

for(const [language,wrong] of [['hu',/2 gyermek, 7 évesek/u],['de',/2 Kinder im Alter von 7 Jahren/u],['en',/2 children, aged 7/u],['si',/2 otroka; starost otrok: 7 let/u]])test(`partial ages do not describe all children as the same age in ${language}`,()=>{const draft=buildReplyDraft({original:'teszt',language,arrival:stay.arrival,departure:stay.departure,guests:4,adults:2,children:2,childAges:[7],cabin:'Deluxe'});assert.doesNotMatch(draft,wrong);});
